#!/usr/bin/env bash

version() {
  echo "Git PR v0.0.2"
}

usage() {
  echo "Open a new PR for the current branch on GitHub"
  echo ""
  echo "Usage: git pr [options]"
}

main() {
  local subcommand="$1"

  case $subcommand in
    "-v"|"--version")
      version
      exit 0
      ;;

    "-h"|"--help")
      usage
      exit 0
      ;;

    *)
      run "$@"
      ;;
  esac

  exit 0
}

getRemoteRepoName() {
  local repoName=$(git remote get-url origin 2> /dev/null | sed -r 's/^.*?github\.com:(.*?)\.git/\1/')

  if [ "$repoName" = "" ]; then
    echo "Not in a repository with a GitHub origin" > /dev/stderr
    return 1
  fi

  echo "$repoName"
  return 0
}

getBranchName() {
  local branchName="$(git name-rev --name-only HEAD 2> /dev/null)"

  if [ "$repoName" = "" ]; then
    echo "Unable to get branch name" > /dev/stderr
    return 1
  fi

  echo "$branchName"
  return 0
}

getNewPrUrl() {
  local repo="$(getRemoteRepoName)"
  local branch="$(getBranchName)"

  if [ "$repo" = "" ] || [ "$branch" = "" ]; then
    return 1
  fi

  echo "https://github.com/$repo/pull/new/$branch"
}

run() {
  local url=$(getNewPrUrl)

  if [ "$url" = "" ]; then
    exit 1
  fi

  xdg-open $url
}

main "$@"
